services:
  # lightrag:
  #   container_name: lightrag
  #   image: ghcr.io/hkuds/lightrag:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     tags:
  #       - ghcr.io/hkuds/lightrag:latest
  #   ports:
  #     - "${PORT:-9621}:9621"
  #   volumes:
  #     - ./data/rag_storage:/app/data/rag_storage
  #     - ./data/inputs:/app/data/inputs
  #     - ./config.ini:/app/config.ini
  #     - ./.env:/app/.env
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  neo4j:
    image: neo4j:5.11.0
    container_name: lightrag-neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - ./data/neo4j_data:/data

  redis:
    image: redis:latest
    container_name: lightrag-redis
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis_data:/data
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: lightrag-redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: lightrag-qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: lightrag-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: lightrag-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped
